title: Social Software Engineering @ INESC-ID
baseurl: ""

date_format: "%Y-%m-%d"

google_analytics:
disqus_shortname:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
